"""One-time, safe ATP schema upgrade for InternMate task planning and attachments."""
from sqlalchemy import inspect, text
from backend.app.main import engine


def main() -> None:
    inspector = inspect(engine)
    project_columns = {column["name"].lower() for column in inspector.get_columns("operations_project")}
    with engine.begin() as conn:
        if "start_date" not in project_columns:
            conn.execute(text("ALTER TABLE operations_project ADD (start_date DATE)"))
        if "end_date" not in project_columns:
            conn.execute(text("ALTER TABLE operations_project ADD (end_date DATE)"))
        if not inspector.has_table("operations_taskattachment"):
            conn.execute(text("""CREATE TABLE operations_taskattachment (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                entry_id NUMBER NOT NULL,
                original_filename VARCHAR2(255) NOT NULL,
                content_type VARCHAR2(100) NOT NULL,
                content_size NUMBER NOT NULL,
                content_blob BLOB NOT NULL,
                created_by_id NUMBER NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                CONSTRAINT taskattachment_entry_fk FOREIGN KEY (entry_id) REFERENCES operations_dailyprogressentry(id),
                CONSTRAINT taskattachment_user_fk FOREIGN KEY (created_by_id) REFERENCES auth_user(id)
            )"""))
    print("ATP schema ready: project dates and task attachments.")


if __name__ == "__main__":
    main()
