import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import ClassicApp from './classicApp';
import { RoleApp } from './roleApp';
import RoleClassicApp from './roleClassicApp';

const unpack = value => Array.isArray(value) ? value : (value.results || []);
const authHeader = () => {
  const value = localStorage.getItem('internmate_basic_auth');
  return value ? { Authorization: `Basic ${value}` } : {};
};
async function request(path) {
  const response = await fetch(path, { headers: authHeader() });
  if (!response.ok) throw new Error(response.status === 401 ? 'Invalid username or password.' : 'Unable to load InternMate data.');
  return response.json();
}
const Pill = ({ tone='info', children }) => <span className={`pill ${tone}`}>{children}</span>;

function Login({ onLogin }) {
  const [username, setUsername] = useState('manager');
  const [password, setPassword] = useState('pass1234');
  const [error, setError] = useState('');
  async function submit(event) {
    event.preventDefault(); setError('');
    const token = btoa(`${username}:${password}`);
    localStorage.setItem('internmate_basic_auth', token);
    try { await request('/api/daily-logs/'); onLogin(username); }
    catch (err) { localStorage.removeItem('internmate_basic_auth'); setError(err.message); }
  }
  return <div className="container py-4 py-md-5"><div className="hero p-4 p-md-5 mb-4"><div className="row g-4 align-items-center"><div className="col-lg-8"><h1 className="display-6 fw-bold mb-3">InternMate Admin Login</h1><p className="lead mb-2">One workspace for intern daily execution, mentor guidance, blocker visibility, and responsible AI usage tracking.</p><p className="text-muted mb-0">Use role accounts to validate intern, mentor, manager, and HR experiences.</p></div><div className="col-lg-4"><div className="soft-card p-3"><h6 className="mb-3">Demo Credentials</h6><div className="small text-muted"><strong>Intern:</strong> intern1</div><div className="small text-muted"><strong>Mentor:</strong> mentor</div><div className="small text-muted mt-1">admin, manager, mentor, hr, intern1, intern2, intern3</div><div className="small mt-2"><strong>Password:</strong> pass1234</div></div></div></div></div><div className="row g-4"><div className="col-lg-5"><div className="soft-card p-4"><h4 className="mb-3">Sign in</h4><form onSubmit={submit}><div className="mb-3"><label className="form-label">Username</label><input className="form-control" value={username} onChange={e=>setUsername(e.target.value)} /></div><div className="mb-3"><label className="form-label">Password</label><input className="form-control" type="password" value={password} onChange={e=>setPassword(e.target.value)} /></div>{error && <div className="alert alert-danger py-2">{error}</div>}<button className="btn btn-success w-100" type="submit">Login</button></form><a className="btn btn-link ps-0 mt-2" href="http://127.0.0.1:8000/">Back to InternMate overview</a></div></div><div className="col-lg-7"><div className="soft-card p-4 h-100"><h5>How InternMate helps interns</h5><ul className="mb-0"><li>Daily planning and progress tracking with clear workflow states.</li><li>Mentor and manager feedback loops to unblock work faster.</li><li>KPI visibility for outcomes, completion, and on-time delivery.</li><li>Responsible AI usage capture with human review accountability.</li></ul></div></div></div></div>;
}

function Header({ page, setPage, username, logout }) {
  const links = ['Dashboard', 'Daily Logs', 'Daily Stats', 'Reports'];
  return <><header className="top-header border-bottom"><nav className="navbar navbar-expand-lg container py-2"><a className="navbar-brand" href="#" onClick={e=>{e.preventDefault();setPage('Dashboard')}}>InternMate</a><div className="navbar-collapse"><ul className="navbar-nav me-auto mb-2 mb-lg-0 gap-1">{links.map(link=><li className="nav-item" key={link}><a className={`nav-link ${page===link?'active':''}`} href="#" onClick={e=>{e.preventDefault();setPage(link)}}>{link}</a></li>)}<li className="nav-item"><a className="nav-link" href="http://127.0.0.1:8000/codex-cli-guide/">CODEX CLI Guide</a></li><li className="nav-item"><a className="nav-link" href="http://127.0.0.1:8000/admin/">Admin</a></li></ul><div className="d-flex align-items-center gap-2"><a className="btn btn-primary btn-sm" href="http://127.0.0.1:8000/daily-logs/new/">+ Log Task</a><span className="small text-muted">{username}</span><button className="btn btn-outline-secondary btn-sm" onClick={logout}>Logout</button></div></div></nav></header></>;
}
function Filters({ interns, projects }) { return <form className="surface-card p-3 mb-3" onSubmit={e=>e.preventDefault()}><div className="row g-2 align-items-end"><div className="col-md-2"><label className="form-label small text-muted mb-1">Date From</label><input className="form-control form-control-sm" type="date" /></div><div className="col-md-2"><label className="form-label small text-muted mb-1">Date To</label><input className="form-control form-control-sm" type="date" /></div><div className="col-md-2"><label className="form-label small text-muted mb-1">Intern</label><select className="form-select form-select-sm"><option value="">All</option>{interns.map(i=><option key={i.id}>{i.intern_code}</option>)}</select></div><div className="col-md-2"><label className="form-label small text-muted mb-1">Project</label><select className="form-select form-select-sm"><option value="">All</option>{projects.map(p=><option key={p.id}>{p.project_name}</option>)}</select></div><div className="col-md-2"><label className="form-label small text-muted mb-1">Blocked</label><select className="form-select form-select-sm"><option value="">All</option><option>Yes</option><option>No</option></select></div><div className="col-12 d-flex gap-2 pt-1"><button className="btn btn-sm btn-primary">Apply Filters</button><button className="btn btn-sm btn-outline-secondary">Reset</button></div></div></form> }
function LogTable({ logs, full=false }) { return <div className="table-wrap table-responsive"><table className="table table-modern table-hover align-middle"><thead><tr><th>Date</th><th>Intern</th><th>Project</th><th>Task</th><th>Workflow</th><th>Completion</th>{full&&<><th>Blocked</th><th>Final Owner</th><th>Action</th></>}</tr></thead><tbody>{logs.map(log=><tr key={log.id}><td>{log.log_date}</td><td>{log.intern_name}</td><td>{log.project_name}</td><td><a href={`http://127.0.0.1:8000/daily-logs/${log.id}/`}>{log.task_name}</a></td><td><Pill>{log.workflow_state}</Pill></td><td>{log.completion_percentage}%</td>{full&&<><td>{log.blocker_flag?<Pill tone="bad">Yes</Pill>:<Pill tone="ok">No</Pill>}</td><td><Pill tone="warn">{log.final_owner}</Pill></td><td><a className="btn btn-sm btn-outline-secondary" href={`http://127.0.0.1:8000/daily-logs/${log.id}/edit/`}>Edit</a></td></>}</tr>)}{!logs.length&&<tr><td colSpan="9" className="text-muted">No logs yet.</td></tr>}</tbody></table></div> }
function Dashboard({ logs, interns, projects }) { const total=logs.length, completed=logs.filter(l=>l.completion_percentage===100).length, blocked=logs.filter(l=>l.blocker_flag).length, avg=total?(logs.reduce((n,l)=>n+l.completion_percentage,0)/total).toFixed(2):0; return <><section className="page-head p-3 p-md-4 mb-3"><div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2"><div><p className="text-uppercase small text-muted mb-1">Overview</p><h3 className="mb-1">Team Progress Dashboard</h3><p className="text-muted mb-0">Track completion, blockers, and AI-assisted productivity in one place.</p></div><a className="btn btn-outline-primary" href="http://127.0.0.1:8000/api/daily-logs/" target="_blank">Open Daily Logs API</a></div></section><Filters interns={interns} projects={projects}/><div className="row g-3 mb-3"><div className="col-sm-6 col-xl-3"><div className="kpi-card one p-3"><div className="kpi-label">Total Tasks</div><div className="kpi-value">{total}</div><div className="small">Across interns</div></div></div><div className="col-sm-6 col-xl-3"><div className="kpi-card two p-3"><div className="kpi-label">Completed Tasks</div><div className="kpi-value">{completed}</div><div className="small">Delivery outcomes</div></div></div><div className="col-sm-6 col-xl-3"><div className="kpi-card three p-3"><div className="kpi-label">Blocked / On Hold</div><div className="kpi-value">{blocked}</div><div className="small">Needs intervention</div></div></div><div className="col-sm-6 col-xl-3"><div className="kpi-card four p-3"><div className="kpi-label">Completion Rate</div><div className="kpi-value">{total?((completed/total)*100).toFixed(2):0}%</div><div className="small">Current cycle</div></div></div></div><div className="surface-card p-3 mb-3"><div className="metric-strip"><div className="metric-item"><div className="small text-muted">Average Completion</div><div className="v">{avg}%</div></div><div className="metric-item"><div className="small text-muted">AI-Assisted Tasks</div><div className="v">-</div></div><div className="metric-item"><div className="small text-muted">Time Saved</div><div className="v">- hrs</div></div><div className="metric-item"><div className="small text-muted">Review Focus</div><div className="v">Mentor Queue</div></div></div></div><div className="surface-card p-3"><div className="d-flex justify-content-between align-items-center mb-2"><h5 className="mb-0">Recent Activity</h5><span className="small text-muted">Latest 10 logs</span></div><LogTable logs={logs.slice(0,10)}/></div></> }
function Logs({ logs, interns, projects }) { return <><section className="page-head p-3 p-md-4 mb-3"><div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2"><div><p className="text-uppercase small text-muted mb-1">Work Journal</p><h3 className="mb-1">Daily Logs</h3><p className="text-muted mb-0">On Hold = blocked or unresolved dependency on others.</p></div><div className="d-flex gap-2"><a className="btn btn-sm btn-primary" href="http://127.0.0.1:8000/daily-logs/new/">+ Log Task</a><Pill tone="bad">Blocked</Pill><Pill tone="warn">On Hold</Pill><Pill tone="ok">Clear</Pill></div></div></section><Filters interns={interns} projects={projects}/><div className="surface-card p-3"><LogTable logs={logs} full/></div></> }
function Stats({ logs, interns, projects }) { const rows=useMemo(()=>Object.values(logs.reduce((all,l)=>{const x=all[l.log_date]||={date:l.log_date,tasks:0,completed:0,blocked:0,total:0};x.tasks++;x.completed+=l.completion_percentage===100;x.blocked+=l.blocker_flag;x.total+=l.completion_percentage;all[l.log_date]=x;return all},{})),[logs]); return <><section className="page-head p-3 p-md-4 mb-3"><p className="text-uppercase small text-muted mb-1">Trend View</p><h3 className="mb-1">Daily Stats</h3><p className="text-muted mb-0">Day-wise productivity, blockers, AI assistance, and effort tracking.</p></section><Filters interns={interns} projects={projects}/><div className="surface-card p-3"><div className="table-wrap table-responsive"><table className="table table-modern table-hover align-middle"><thead><tr><th>Date</th><th>Tasks Logged</th><th>Completed</th><th>Blocked</th><th>Avg Completion</th><th>AI-Assisted</th><th>Time Spent</th><th>Time Saved</th></tr></thead><tbody>{rows.map(r=><tr key={r.date}><td>{r.date}</td><td>{r.tasks}</td><td>{r.completed}</td><td><Pill tone={r.blocked?'bad':'ok'}>{r.blocked}</Pill></td><td>{(r.total/r.tasks).toFixed(2)}%</td><td>-</td><td>-</td><td>-</td></tr>)}</tbody></table></div></div></> }
function Reports({ logs, interns, projects }) { const rows=Object.values(logs.reduce((all,l)=>{const x=all[l.intern_profile]||={code:l.intern_profile,name:l.intern_name,total:0,completed:0,blocked:0,progress:0};x.total++;x.completed+=l.completion_percentage===100;x.blocked+=l.blocker_flag;x.progress+=l.completion_percentage;all[l.intern_profile]=x;return all},{})); return <><section className="page-head p-3 p-md-4 mb-3"><div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2"><div><p className="text-uppercase small text-muted mb-1">Analytics</p><h3 className="mb-1">Intern Performance Reports</h3><p className="text-muted mb-0">Export stakeholder-ready summaries in CSV, XLSX, or PDF.</p></div><div className="d-flex gap-2"><a className="btn btn-outline-secondary btn-sm" href="http://127.0.0.1:8000/reports/export/?format=csv">CSV</a><a className="btn btn-outline-secondary btn-sm" href="http://127.0.0.1:8000/reports/export/?format=xlsx">XLSX</a><a className="btn btn-primary btn-sm" href="http://127.0.0.1:8000/reports/export/?format=pdf">PDF</a></div></div></section><Filters interns={interns} projects={projects}/><div className="surface-card p-3"><div className="table-wrap table-responsive"><table className="table table-modern table-hover align-middle"><thead><tr><th>Intern Code</th><th>Name</th><th>Total</th><th>Completed</th><th>Blocked</th><th>Avg Completion</th><th>Time Saved</th></tr></thead><tbody>{rows.map(r=><tr key={r.code}><td>{r.code}</td><td>{r.name}</td><td>{r.total}</td><td>{r.completed}</td><td><Pill tone={r.blocked?'bad':'ok'}>{r.blocked}</Pill></td><td>{(r.progress/r.total).toFixed(2)}%</td><td>-</td></tr>)}</tbody></table></div></div></> }
function App(){const [username,setUsername]=useState(localStorage.getItem('internmate_username')||''),[page,setPage]=useState('Dashboard'),[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{if(!username)return;Promise.all([request('/api/daily-logs/'),request('/api/interns/'),request('/api/projects/')]).then(([l,i,p])=>setData({logs:unpack(l),interns:unpack(i),projects:unpack(p)})).catch(e=>{setError(e.message);localStorage.removeItem('internmate_basic_auth');setUsername('')})},[username]);if(!username)return <Login onLogin={name=>{localStorage.setItem('internmate_username',name);setUsername(name)}}/>;if(!data)return <div className="container py-5 text-muted">Loading InternMate… {error}</div>;const common={logs:data.logs,interns:data.interns,projects:data.projects};const view=page==='Dashboard'?<Dashboard {...common}/>:page==='Daily Logs'?<Logs {...common}/>:page==='Daily Stats'?<Stats {...common}/>:<Reports {...common}/>;return <><Header page={page} setPage={setPage} username={username} logout={()=>{localStorage.removeItem('internmate_basic_auth');localStorage.removeItem('internmate_username');setUsername('');setData(null)}}/><main className="container py-4">{view}</main><footer className="app-footer border-top mt-4"><div className="container py-3 d-flex flex-column flex-md-row justify-content-between gap-2"><span className="text-muted small">InternMate | Daily Work Enablement, Mentor Guidance, KPI Visibility, Responsible AI</span><span className="text-muted small">UX Refresh v2</span></div></footer></>}
// Preserve the morning UI and add only the requested role-specific actions.
createRoot(document.getElementById('root')).render(<RoleClassicApp/>);
