# Generated by Django 6.0.4 on 2026-04-22 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterDataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['list_ref', 'display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='MasterDataList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('action_type', models.CharField(max_length=30)),
                ('old_value_json', models.JSONField(blank=True, default=dict)),
                ('new_value_json', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern_code', models.CharField(max_length=40, unique=True)),
                ('internship_start_date', models.DateField()),
                ('internship_end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_interns', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentored_interns', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, to='operations.skilldomain')),
            ],
            options={
                'ordering': ['intern_code'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('planned_work', models.TextField(blank=True)),
                ('actual_work', models.TextField(blank=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('workflow_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('blocker_flag', models.BooleanField(default=False)),
                ('blocker_description', models.TextField(blank=True)),
                ('support_needed', models.TextField(blank=True)),
                ('time_spent_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('deliverable_link', models.URLField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('on_time_completion_flag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('intern_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='operations.internprofile')),
                ('completion_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_status_entries', to='operations.masterdataitem')),
                ('final_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_owner_entries', to='operations.masterdataitem')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priority_entries', to='operations.masterdataitem')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_type_entries', to='operations.masterdataitem')),
            ],
            options={
                'ordering': ['-log_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_contribution_percentage', models.PositiveSmallIntegerField(default=0)),
                ('prompt_summary', models.TextField(blank=True)),
                ('accuracy_helpfulness_rating', models.PositiveSmallIntegerField(default=0)),
                ('estimated_time_saved_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_ai_flag', models.BooleanField(default=False)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='operations.dailyprogressentry')),
                ('ai_assistance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_assistance_entries', to='operations.masterdataitem')),
                ('ai_tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_tool_entries', to='operations.masterdataitem')),
                ('human_review_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_review_entries', to='operations.masterdataitem')),
                ('output_usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_usage_entries', to='operations.masterdataitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='masterdataitem',
            name='list_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.masterdatalist'),
        ),
        migrations.CreateModel(
            name='MentorReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed')], max_length=20)),
                ('comment_text', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='operations.dailyprogressentry')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.CharField(max_length=40, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.department')),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
        migrations.AddField(
            model_name='dailyprogressentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.project'),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_text', models.CharField(max_length=255)),
                ('dependency_status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='operations.dailyprogressentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='masterdataitem',
            unique_together={('list_ref', 'value')},
        ),
        migrations.CreateModel(
            name='InternProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_from', models.DateField()),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('intern_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='operations.internprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_assignments', to='operations.project')),
            ],
            options={
                'unique_together': {('intern_profile', 'project', 'assigned_from')},
            },
        ),
    ]
